apiVersion: v1
kind: Secret
metadata:
  name: glpi-secrets
  namespace: client-bornan
type: Opaque
stringData:
  MYSQL_HOST: "mysql-internal.shared.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "glpidb"
  MYSQL_USER: "glpi"
  MYSQL_PASSWORD: "jf5y2PhgB3tfm9k"
